name: Build and Release Windows
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install
          npm install @rollup/rollup-win32-x64-msvc

      - name: Build and Publish
        run: npx electron-builder --windows --publish always
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
